kind = "mobile"
previewPath = "/"
title = "QueueCast"
version = "1.0.0"
id = "artifacts/queuecast"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23859

[services.development]
run = "pnpm --filter @workspace/queuecast run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/queuecast", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/queuecast", "run", "serve" ]

[services.env]
PORT = "23859"
BASE_PATH = "/"
